major_keys = {
  "C":  ["C", "Dm", "Em", "F", "G", "Am", "B"],
  "C#": ["C#", "D#m", "E#m", "F#", "G#", "A#m", "B#"],
  "Db": ["Db", "Ebm", "F", "Gb", "Ab", "Bbm", "C"],
  "D":  ["D", "Em", "F#m", "G", "A", "Bm", "C#"],
  "Eb": ["Eb", "Fm", "Gm", "Ab", "Bb", "Cm", "D"],
  "E":  ["E", "F#m", "G#m", "A", "B", "C#m", "D#"],
  "F":  ["F", "Gm", "Am", "Bb", "C", "Dm", "E"],
  "F#": ["F#", "G#m", "A#m", "B", "C#", "D#m", "E#"],
  "Gb": ["Gb", "Abm", "Bbm", "Cb", "Db", "Ebm", "F"],
  "G":  ["G", "Am", "Bm", "C", "D", "Em", "F#"],
  "Ab": ["Ab", "Bbm", "Cm", "Db", "Eb", "Fm", "G"],
  "A":  ["A", "Bm", "C#m", "D", "E", "F#m", "G#"],
  "Bb": ["Bb", "Cm", "Dm", "Eb", "F", "Gm", "A"],
  "B":  ["B", "C#m", "D#m", "E", "F#", "G#m", "A#"],
}

minor_keys = {
  "Cm":  ["Cm", "Db", "Eb", "Fm", "Gm", "Ab", "Bb"],
  "C#m": ["C#m", "D", "E", "F#m", "G#m", "A", "B"],
  "Dm":  ["Dm", "Eb", "F", "Gm", "Am", "Bb", "C"],
  "D#m": ["D#m", "E", "F#", "G#m", "A#m", "B", "C#"],
  "Em":  ["Em", "F", "G", "Am", "Bm", "C", "D"],
  "Fm":  ["Fm", "Gb", "Ab", "Bbm", "Cm", "Db", "Eb"],
  "F#m": ["F#m", "G", "A", "Bm", "C#m", "D", "E"],
  "Gm":  ["Gm", "Ab", "Bb", "Cm", "Dm", "Eb", "F"],
  "G#m": ["G#m", "A", "B", "C#m", "D#m", "E", "F#"],
  "Am":  ["Am", "Bb", "C", "Dm", "Em", "F", "G"],
  "A#m": ["A#m", "B", "C#", "D#m", "E#m", "F#", "G#"],
  "Bm":  ["Bm", "C", "D", "Em", "F#m", "G", "A"],
}